### PR TITLE
Use openssl for blowfish, md5 and random IVs

### PR DESCRIPTION
**Pull request by kenohassler**
Since homebrew now flags libmcrypt as deprecated (https://formulae.brew.sh/formula/mcrypt) and it is largely considered abandonware, I took the liberty to port the Blowfish code to libcrypto, provided by OpenSSL / LibreSSL.
Pulling in OpenSSL also gives us the opportunity to remove the custom MD5 implementation and provides a portable way to get crypto-secure randomness, which I used to re-implement the random IV proposal from #22.

### CODE REVIEW

**Comment by pyropeter** [comment]
The following is not meant as an critique or endorsement of this PR; I merely want to stop by quickly, add some incoherent remarks, and then vanish again.

I originally removed the openssl dependency (in 2010!), because people were running otrtool on home routers running OpenWRT. Those routers usually featured, if I recall correctly, 4MB of flash storage, which back in the day was able to fit linux, networking utils, lua, the web frontend, libmcrypt, libcurl, and otrtool. (But not openssl) People seemed to use those routers as some kind of media server, paired with an external USB hard drive.

Okay, that were my two cents; I will now let my handlers return me to the retirement home. 🧓

**Comment by kenohassler** [comment]
Hi, thanks for your feedback, I appreciate it!
I didn't consider such low-powered devices indeed. The question is, is this still a problem in 2022?
I imagine "modern" home routers do not run on 4MB flash anymore? 😅

**Comment by eshrdlu** [comment]
@PyroPeter:
> The following is not meant as an critique or endorsement of this PR; [...]

I will neither confirm nor deny that your comment has influenced my opinion.
(Nice to hear from you again.)

@kenohassler:
Thanks for your pull request, it has definitely sparked some activity.

https://sourceforge.net/projects/mcrypt/ says last update 2012-09-14,
so yeah, either abandoned or they are even slower to respond than I am...
I don't know much about OpenSSL or libcrypto. Just from looking at Debian
packages, it seems multiple times heavier than libmcrypt.
Regardless of whether those home routers still exist, I would like
to keep dependencies as minimal as possible.

Therefore, I have now re-implemented the Blowfish algorithm from the
original paper (couldn't find a public domain C implementation quickly),
so that we can remove the libmcrypt dependency without creating a new one.
(see above commit)

I could not test CBC decryption (server response) yet;
server requests and file decryption work for me.

Regarding random IVs (PR #22):
IMUO* this doesn't fix OTR's inherently insecure custom protocol, which
we cannot change. I would rather consider - optionally - using TLS for
the server communication. The only downside with this would be that,
iirc, official decoders don't use HTTPS, making otrtool more distinguishable.

*) in my uneducated opinion

**Comment by kenohassler** [comment]
Great to see this problem solved - I guess, now there *is* a public domain implementation 😄
Nice side effect of shipping with blowfish included is that otrtool should now build ootb on macOS.

Regarding security: The protocol is garbage and it's not on us to fix it. I think it's fair to use self-coded crypto here ^^
It could be an option to use getentropy() for portable random IVs. Should work on Linux and BSDs (incl. macOS). But the security benefit is rather small 😁

**Comment by eshrdlu** [comment]
Update: Of course I got the CBC decryption wrong.
Rebased, squashed and merged my temporary branch into master.

**Pull request closed without merging**
