### PR TITLE
Switched from unnamed to named semaphores

### PR DESCRIPTION
**Pull request by Tormen**
Switched from unnamed to named semaphores to allow compilation under MacOS (Catalina).
MacOS does not support (anymore?) unnamed semaphores.

### CODE REVIEW

**Comment by not-a-user** [comment]
Must use names other than `/semaphore.read` etc. to prevent name clashes with other software. What about `/otrtool.read` etc.?

**Comment by not-a-user** [comment]
I encourage you to keep this thing running on the Macintosh! - So please fix the pointer bugs you introduced:

```
$ make
cc  -O3 -Wall -Wextra -g -pthread -DVERSION='"v1.2.1-4-gf53d8cb"'  -c src/main.c -o src/main.o
src/main.c: In function 'decryptFileWorker':
src/main.c:922:12: warning: passing argument 1 of 'sem_wait' from incompatible pointer type [-Wincompatible-pointer-types]
  922 |   sem_wait(&w->read_sema);
      |            ^~~~~~~~~~~~~
      |            |
      |            sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:55:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   55 | extern int sem_wait (sem_t *__sem) __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:932:14: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
  932 |     sem_post(&w->next->read_sema);
      |              ^~~~~~~~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:934:14: warning: passing argument 1 of 'sem_wait' from incompatible pointer type [-Wincompatible-pointer-types]
  934 |     sem_wait(&w->ivfy_sema);
      |              ^~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:55:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   55 | extern int sem_wait (sem_t *__sem) __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:936:14: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
  936 |     sem_post(&w->next->ivfy_sema);
      |              ^~~~~~~~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:942:14: warning: passing argument 1 of 'sem_wait' from incompatible pointer type [-Wincompatible-pointer-types]
  942 |     sem_wait(&w->ovfy_sema);
      |              ^~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:55:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   55 | extern int sem_wait (sem_t *__sem) __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:944:14: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
  944 |     sem_post(&w->next->ovfy_sema);
      |              ^~~~~~~~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:946:14: warning: passing argument 1 of 'sem_wait' from incompatible pointer type [-Wincompatible-pointer-types]
  946 |     sem_wait(&w->write_sema);
      |              ^~~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:55:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   55 | extern int sem_wait (sem_t *__sem) __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:950:14: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
  950 |     sem_post(&w->next->write_sema);
      |              ^~~~~~~~~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:952:14: warning: passing argument 1 of 'sem_wait' from incompatible pointer type [-Wincompatible-pointer-types]
  952 |     sem_wait(&w->read_sema);
      |              ^~~~~~~~~~~~~
      |              |
      |              sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:55:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   55 | extern int sem_wait (sem_t *__sem) __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:954:12: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
  954 |   sem_post(&w->next->read_sema);
      |            ^~~~~~~~~~~~~~~~~~~
      |            |
      |            sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c: In function 'decryptFile':
src/main.c:1055:12: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
 1055 |   sem_post(&wrk_info[0].read_sema);
      |            ^~~~~~~~~~~~~~~~~~~~~~
      |            |
      |            sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:1056:12: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
 1056 |   sem_post(&wrk_info[0].ivfy_sema);
      |            ^~~~~~~~~~~~~~~~~~~~~~
      |            |
      |            sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:1057:12: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
 1057 |   sem_post(&wrk_info[0].ovfy_sema);
      |            ^~~~~~~~~~~~~~~~~~~~~~
      |            |
      |            sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
src/main.c:1058:12: warning: passing argument 1 of 'sem_post' from incompatible pointer type [-Wincompatible-pointer-types]
 1058 |   sem_post(&wrk_info[0].write_sema);
      |            ^~~~~~~~~~~~~~~~~~~~~~~
      |            |
      |            sem_t **
In file included from src/main.c:12:
/usr/include/semaphore.h:78:29: note: expected 'sem_t *' but argument is of type 'sem_t **'
   78 | extern int sem_post (sem_t *__sem) __THROWNL __nonnull ((1));
      |                      ~~~~~~~^~~~~
cc  -O3 -Wall -Wextra -g -pthread -DVERSION='"v1.2.1-4-gf53d8cb"'  -o otrtool src/md5.o src/main.o -lmcrypt -lcurl 
Build successful
Done.
```

Your version will coredump immediately:

```
$ ~/scratch/git/otrtool/otrtool -x -e user@site.com -p PASSWORD -D . ~/Downloads/Die_Simpsons_20.06.29_20-15_pro7_30_TVOON_DE.mpg.HQ.avi.otrkey 
OTR-Tool, v1.2.1-4-gf53d8cb
Trying to contact server...
Server responded.
Keyphrase: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
info: saved keyphrase to ~/.otrkey_cache
Decrypting and verifying...
The futex facility returned an unexpected error code.
Aborted (core dumped)

```

**Comment by Tormen** [comment]
Hi Scott,

Thanks for your mail! :))

Just, I am not sure I understand: For me it compiled and runs fine without core dump... or are the error messages from a Linux machine ?

But in any case I'll have another look hopefully next weekend.

Tormen

--

**Comment by not-a-user** [comment]
I get the same result when cloning https://github.com/Tormen/otrtool on both Arch and Fedora. The compiler messages are plain, and the crash is just the logical consequence. I cannot imagine that OSX can deal with that. Please double check.

**Comment by eshrdlu** [comment]
By setting `n_wrk_max` to 1, there is only one worker thread, which defies the purpose of multithreading. As far as my understanding goes, if we were to use named semaphores, each thread would have to use a unique name. Unnamed semaphores seem more convenient to me.

As of commit bccb619, it should be possible again to compile otrtool on systems that don't fully support POSIX semaphores. In this case, multithreading will be disabled. If someone desperately wants to support multilthreading on such systems, they could do so by defining a new set of wrapper functions.

Happy New Year!

**Comment by eshrdlu** [comment]
I should probably add that I do not have access to a MacOS machine for testing.
If otrtool should still fail to compile under MacOS (or any not ancient unix-like system), this is of course considered a bug, and reports are much appreciated.

**Pull request closed without merging**
